const GAMES={"6/42":{name:"Lotto 6/42",max:42,aliases:["6/42","642","LOTTO 42","LOTTO6/42"]},"6/45":{name:"Mega Lotto 6/45",max:45,aliases:["6/45","645","MEGA LOTTO","ML45"]},"6/49":{name:"Super Lotto 6/49",max:49,aliases:["6/49","649","SUPER LOTTO","SL49"]},"6/55":{name:"Grand Lotto 6/55",max:55,aliases:["6/55","655","GRAND LOTTO","GL55"]},"6/58":{name:"Ultra Lotto 6/58",max:58,aliases:["6/58","658","ULTRA LOTTO","UL58"]}};
let resultsData=null,historyData=null,lineCounter=0;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function fmtDate(iso){if(!iso)return"Unknown date";const d=new Date(iso+"T00:00:00+08:00");return new Intl.DateTimeFormat("en-PH",{year:"numeric",month:"short",day:"numeric",timeZone:"Asia/Manila"}).format(d)}
function ball(n,match=false){return `<span class="ball${match?' match':''}">${String(n).padStart(2,'0')}</span>`}
function fillGameSelect(el){el.innerHTML=Object.entries(GAMES).map(([id,g])=>`<option value="${id}">${g.name}</option>`).join("")}
async function loadData(){try{const [r,h]=await Promise.all([fetch('data/results.json',{cache:'no-store'}),fetch('data/history.json',{cache:'no-store'})]);resultsData=await r.json();historyData=await h.json();renderResults();syncDrawOptions();updateHistoryCount()}catch(e){console.error(e);$('#dataFreshness').textContent='Result data could not be loaded. Use the official PCSO source link below.'}}
function renderResults(){const grid=$('#resultsGrid');grid.innerHTML=Object.entries(GAMES).map(([id,g])=>{const r=resultsData.games[id];if(!r)return'';return `<article class="result-card"><div class="game">${g.name}</div><div class="date">${fmtDate(r.date)}</div><div class="balls">${r.numbers.map(n=>ball(n)).join('')}</div><div class="jackpot">${r.jackpot||'Jackpot not stored'}</div><div class="winners">${Number.isFinite(r.winners)?`${r.winners} jackpot winner${r.winners===1?'':'s'}`:'Winner count unavailable'}</div></article>`}).join('');const updated=resultsData.updated_at?new Date(resultsData.updated_at).toLocaleString('en-PH',{timeZone:'Asia/Manila',dateStyle:'medium',timeStyle:'short'}):'unknown';$('#dataFreshness').textContent=`Local result file updated ${updated}. Always verify against PCSO.`}
function allDraws(game){const list=[...(historyData?.games?.[game]||[])];const latest=resultsData?.games?.[game];if(latest&&!list.some(x=>x.date===latest.date&&x.numbers.join()==latest.numbers.join()))list.unshift({date:latest.date,numbers:latest.numbers,jackpot:latest.jackpot,winners:latest.winners});return list.sort((a,b)=>b.date.localeCompare(a.date))}
function syncDrawOptions(){if(!resultsData||!historyData)return;const game=$('#scanGame').value;const draws=allDraws(game);$('#drawSelect').innerHTML=draws.map((d,i)=>`<option value="${i}">${fmtDate(d.date)} — ${d.numbers.map(n=>String(n).padStart(2,'0')).join(' ')}</option>`).join('')}
function addPlayLine(values=[]){lineCounter++;const max=GAMES[$('#scanGame').value]?.max||58;const wrap=document.createElement('div');wrap.className='play-line';wrap.innerHTML=`<span class="line-no">${lineCounter}</span><div class="number-inputs">${Array.from({length:6},(_,i)=>`<input inputmode="numeric" aria-label="Number ${i+1}" min="1" max="${max}" maxlength="2" value="${values[i]??''}">`).join('')}</div><button class="remove-line" type="button" aria-label="Remove line">×</button>`;wrap.querySelector('.remove-line').addEventListener('click',()=>{wrap.remove();renumberLines()});$('#ticketLines').appendChild(wrap)}
function renumberLines(){lineCounter=0;$$('.play-line').forEach(row=>{lineCounter++;row.querySelector('.line-no').textContent=lineCounter})}
function clearLines(){lineCounter=0;$('#ticketLines').innerHTML=''}
function readLines(){const max=GAMES[$('#scanGame').value].max;return $$('.play-line').map((row,idx)=>{const nums=[...row.querySelectorAll('input')].map(i=>Number(i.value));const valid=nums.length===6&&nums.every(n=>Number.isInteger(n)&&n>=1&&n<=max)&&new Set(nums).size===6;return{index:idx+1,nums,valid}})}
function checkTicket(){if(!historyData)return;const game=$('#scanGame').value,draws=allDraws(game),draw=draws[Number($('#drawSelect').value)||0],lines=readLines(),out=$('#checkResults');if(!draw){out.innerHTML='<div class="status error">No draw data is available for this game.</div>';return}if(!lines.length){out.innerHTML='<div class="status error">Add at least one play line.</div>';return}out.innerHTML=lines.map(line=>{if(!line.valid)return `<div class="check-card"><div class="check-title"><strong>Line ${line.index}</strong><span>Needs correction</span></div><div class="result-message">Enter six different numbers from 1 to ${GAMES[game].max}.</div></div>`;const hits=line.nums.filter(n=>draw.numbers.includes(n));let msg=hits.length>=6?'6/6 jackpot-combination match — preserve the original ticket and verify immediately with PCSO.':hits.length>=3?`${hits.length}/6 match — potentially prize-eligible; verify the original ticket with PCSO or an authorized outlet.`:`${hits.length}/6 match — no 3+ number match on this line.`;return `<div class="check-card ${hits.length>=3?'win':''}"><div class="check-title"><strong>Line ${line.index}</strong><span>${hits.length}/6 matched</span></div><div class="balls">${line.nums.map(n=>ball(n,hits.includes(n))).join('')}</div><div class="result-message">${msg}</div></div>`}).join('')}
function detectGame(text){const u=text.toUpperCase().replace(/\s+/g,' ');for(const [id,g] of Object.entries(GAMES)){if(g.aliases.some(a=>u.includes(a)))return id}return null}
function normalizeOcrLine(line){return line.replace(/[Oo]/g,'0').replace(/(?<=\s)[Il|](?=\s|$)/g,'1')}
function extractPlayLines(text,game){const max=GAMES[game].max;const rows=[];for(const raw of text.split(/\n+/)){const line=normalizeOcrLine(raw);const nums=(line.match(/\b\d{1,2}\b/g)||[]).map(Number).filter(n=>n>=1&&n<=max);if(nums.length===6&&new Set(nums).size===6)rows.push(nums)}if(rows.length)return rows.slice(0,12);const nums=(normalizeOcrLine(text).match(/\b\d{1,2}\b/g)||[]).map(Number).filter(n=>n>=1&&n<=max);for(let i=0;i+5<nums.length&&rows.length<8;i++){const chunk=nums.slice(i,i+6);if(new Set(chunk).size===6){rows.push(chunk);i+=5}}return rows}
async function scanPhoto(file){const status=$('#ocrStatus'),preview=$('#preview');preview.src=URL.createObjectURL(file);preview.classList.remove('hidden');status.classList.remove('hidden','error');status.textContent='Preparing OCR…';if(!window.Tesseract){status.classList.add('error');status.textContent='OCR library did not load. You can still enter the six numbers manually.';return}try{const result=await Tesseract.recognize(file,'eng',{logger:m=>{if(m.status==='recognizing text')status.textContent=`Reading ticket… ${Math.round((m.progress||0)*100)}%`;else status.textContent=m.status.replace(/_/g,' ')}});const text=result.data.text||'';$('#rawOcr').textContent=text;$('#rawOcrWrap').classList.remove('hidden');const detected=detectGame(text);if(detected){$('#scanGame').value=detected;syncDrawOptions()}const game=$('#scanGame').value;const lines=extractPlayLines(text,game);if(lines.length){clearLines();lines.forEach(addPlayLine);status.textContent=`Found ${lines.length} possible play line${lines.length===1?'':'s'}. Review every number before checking.`}else{status.classList.add('error');status.textContent='I could not confidently find a six-number play line. Try a clearer photo or enter the numbers manually.'}}catch(e){console.error(e);status.classList.add('error');status.textContent='OCR failed on this image. You can still enter the numbers manually.'}}
function cryptoRandom(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296}
function weightedPick(items,weights){let total=weights.reduce((a,b)=>a+b,0),r=cryptoRandom()*total;for(let i=0;i<items.length;i++){r-=weights[i];if(r<=0)return i}return items.length-1}
function historySuggested(game){const max=GAMES[game].max,draws=allDraws(game),freq=Array(max+1).fill(0);draws.forEach(d=>d.numbers.forEach(n=>freq[n]++));const pool=Array.from({length:max},(_,i)=>i+1),picked=[];while(picked.length<6){const weights=pool.map(n=>1+0.18*(draws.length?freq[n]/Math.max(1,draws.length)*6:0));const idx=weightedPick(pool,weights);picked.push(pool[idx]);pool.splice(idx,1)}return picked.sort((a,b)=>a-b)}
function uniformSuggested(game){const pool=Array.from({length:GAMES[game].max},(_,i)=>i+1),out=[];while(out.length<6){const idx=Math.floor(cryptoRandom()*pool.length);out.push(pool.splice(idx,1)[0])}return out.sort((a,b)=>a-b)}
function balancedSuggested(game){const max=GAMES[game].max;for(let tries=0;tries<100;tries++){const p=uniformSuggested(game),odd=p.filter(n=>n%2).length,low=p.filter(n=>n<=Math.ceil(max/2)).length,consecutive=p.slice(1).filter((n,i)=>n-p[i]===1).length;if(odd>=2&&odd<=4&&low>=2&&low<=4&&consecutive<=1)return p}return uniformSuggested(game)}
function generateSuggestions(){const game=$('#suggestGame').value,mode=$('#suggestMode').value;const fn=mode==='history'?historySuggested:mode==='balanced'?balancedSuggested:uniformSuggested;const picks=Array.from({length:5},()=>fn(game));$('#suggestions').innerHTML=picks.map((p,i)=>`<div class="suggestion-row"><div><small>Pick ${i+1}</small><div class="balls">${p.map(n=>ball(n)).join('')}</div></div><button class="copy-pick" data-copy="${p.join('-')}">Copy</button></div>`).join('');$$('.copy-pick').forEach(b=>b.addEventListener('click',async()=>{await navigator.clipboard.writeText(b.dataset.copy);const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,900)}))}
function updateHistoryCount(){if(!historyData)return;const g=$('#suggestGame').value;$('#historyCount').textContent=`Stored sample: ${allDraws(g).length} verified draw${allDraws(g).length===1?'':'s'}. Add a fuller history file for richer frequency statistics.`}
function init(){fillGameSelect($('#scanGame'));fillGameSelect($('#suggestGame'));$('#scanGame').value='6/45';$('#suggestGame').value='6/45';addPlayLine();$('#addLine').addEventListener('click',()=>addPlayLine());$('#checkTicket').addEventListener('click',checkTicket);$('#scanGame').addEventListener('change',()=>{syncDrawOptions();$$('.number-inputs input').forEach(i=>i.max=GAMES[$('#scanGame').value].max)});$('#ticketPhoto').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)scanPhoto(f)});$('#suggestGame').addEventListener('change',updateHistoryCount);$('#generatePicks').addEventListener('click',generateSuggestions);loadData().then(generateSuggestions);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
document.addEventListener('DOMContentLoaded',init);
